### ISSUE TITLE
Excuse me, each server ID can only use up to 40 reportbot in a game, right?

### ISSUE THREAD

**Issue by moge2019** [despa1r1337/ReportBot-v2#3]
![QQ图片20191211014543](https://user-images.githubusercontent.com/54233256/70554242-bfdb3200-1bb7-11ea-9822-a509656cad4a.png)
As shown in the figure above, after I use 40 reportbot, there will be errors when I use the robot again. This reportbot limits the number of robots, right?
Or something else?

**Comment by despa1r1337** [comment]
> ![QQ图片20191211014543](https://user-images.githubusercontent.com/54233256/70554242-bfdb3200-1bb7-11ea-9822-a509656cad4a.png)
> As shown in the figure above, after I use 40 reportbot, there will be errors when I use the robot again. This reportbot limits the number of robots, right?
> Or something else?

1) have you updated the version? there were changes yesterday. Download the program
2) do you have a link to your account in config.json in "target"?

**Comment by moge2019** [comment]
I don't have an updated version. I just downloaded the latest version from you.
![20191211021953](https://user-images.githubusercontent.com/54233256/70556797-8ce76d00-1bbc-11ea-9f6c-6bb233132c0f.png)
This is my previous setup.

**Comment by despa1r1337** [comment]
> I don't have an updated version. I just downloaded the latest version from you.
> ![20191211021953](https://user-images.githubusercontent.com/54233256/70556797-8ce76d00-1bbc-11ea-9f6c-6bb233132c0f.png)
> This is my previous setup.

try to put after 811 `/`

**Comment by moge2019** [comment]
“try to put after 811”
Sorry, please forgive me for my bad computer technology and English. I don't understand what you said. I don't know how to operate it.

**Comment by despa1r1337** [comment]
Are you trying to reporter this account? https://steamcommunity.com/id/ruijieee/?

**Comment by moge2019** [comment]
Yes, I want to report this account. Sometimes there are 4 to 5 in a game that need to be reported. If I report two people before updating, I can't report them.This kind of situation is not many, but every day there will be several times met opposite 4 to 5 are cheaters.

**Comment by despa1r1337** [comment]
![image](https://user-images.githubusercontent.com/48297813/70558353-c6f14880-1b95-11ea-80e8-94e79bd95993.png)
try so

**Comment by despa1r1337** [comment]
> OK, I'll try.

do you report during the match? or after?

**Comment by moge2019** [comment]
I report it in the game.
It's invalid to report after the game.

**Comment by despa1r1337** [comment]
> I report it in the game.
> It's invalid to report after the game.


ok, did you download the new version?

**Comment by moge2019** [comment]
Thank you so much for your update! I downloaded the latest version an hour ago!

**Comment by despa1r1337** [comment]
do you manage to report? or do you constantly have any errors?

**Comment by moge2019** [comment]
I haven't tried the updated version because it's 3 o'clock in the morning.
I reported the old version successfully, but I can only use it twice. Two times later, something went wrong!

**Comment by despa1r1337** [comment]
what exactly is wrong? why two times? what errors do you get?

**Comment by moge2019** [comment]
After the old version used 40 reporbots, it can no longer be used!
The problem is shown in the figure below.
![20191211014543](https://user-images.githubusercontent.com/54233256/70559694-206f6c80-1bc2-11ea-8a07-b7d9d05ac0de.png)

**Comment by moge2019** [comment]
Please forgive me for my poor English! 
What I want to say is that you can only use the old version twice a day!
I haven't used your updated version!

**Comment by despa1r1337** [comment]
> Please forgive me for my poor English!
> I want to say that the old version can only be used twice a day! 40 reporting robots twice.
> I haven't used the updated version yet.

I understand. When morning comes, please re-download everything. If you have any questions, please contact.

**Comment by moge2019** [comment]
Thank you very much for your patience!
 I'm going to bed!
 When I wake up tomorrow, I will download and use the new version. 
If you have any questions, please ask again!

**Comment by despa1r1337** [comment]
ok ;)

**Comment by despa1r1337** [comment]
> Thank you very much for your patience!
> I'm going to bed!
> When I wake up tomorrow, I will download and use the new version.
> If I have any questions, I will ask you again!

solved?

**Comment by moge2019** [comment]
Thank you very much for your attention。
There will still be a failure to link the sever ID,
 but you can continue to use it by clicking several times.
It's as if the number of reports in a server ID can't be more than one. 
It seems that the number of reports in sever ID cannot be too many. I don't know if there is a limit, such as the maximum number of report BOT or the maximum number of reports.

**Comment by moge2019** [comment]
![QQ图片20191225061140](https://user-images.githubusercontent.com/54233256/71425884-28a8cb00-26dd-11ea-84a2-eceaaa3356f1.png)

**Comment by despa1r1337** [comment]
show your config

**Comment by despa1r1337** [comment]
> Thank you very much for your attention。
> When the number of reports is more than 3, the server ID cannot be connected will appear
> but you can continue to use it by clicking several times.
> It's as if the number of reports in a server ID can't be more than one.
> It seems that the number of reports in sever ID cannot be too many. I don't know if there is a limit, such as the maximum number of report BOT or the maximum number of reports.

show your config

**Comment by moge2019** [comment]
There have been such mistakes recently. Can we solve them?

![2020 01 10](https://user-images.githubusercontent.com/54233256/72090810-bc1f0480-3349-11ea-85e1-58a9bfada5c1.png)
There have been repeated such mistakes, the reporting robot can not be used!
![20200110013903](https://user-images.githubusercontent.com/54233256/72090948-07d1ae00-334a-11ea-890f-819a3f1c6738.png)
Above is my configuration.

**Comment by despa1r1337** [comment]
> There have been such mistakes recently. Can we solve them?
> 
> ![2020 01 10](https://user-images.githubusercontent.com/54233256/72090810-bc1f0480-3349-11ea-85e1-58a9bfada5c1.png)
> There have been repeated such mistakes, the reporting robot can not be used!
> ![20200110013903](https://user-images.githubusercontent.com/54233256/72090948-07d1ae00-334a-11ea-890f-819a3f1c6738.png)
> Above is my configuration.

1. check your accounts, they have the game `Counter-Strike: Global Offensive` in the library

Check your `internet`.

Check if you specified the correct `Steam API KEY`

!!!You need to report during the match, not after it.

**Comment by despa1r1337** [comment]
are you using the latest version of the program?

If not, then download.

Below shows how to install
![image](https://user-images.githubusercontent.com/48297813/72143414-bce68380-33a7-11ea-9c8b-4d276e5e91e6.png)

![image](https://user-images.githubusercontent.com/48297813/72143507-ddaed900-33a7-11ea-942e-fcad2383c117.png)

![image](https://user-images.githubusercontent.com/48297813/72143546-f0c1a900-33a7-11ea-9ca5-8273c7660eb6.png)

![image](https://user-images.githubusercontent.com/48297813/72143562-fae3a780-33a7-11ea-9374-4394f5cd09b2.png)

**Comment by despa1r1337** [comment]
![Безымянный](https://user-images.githubusercontent.com/48297813/72144281-5c584600-33a9-11ea-9b9b-e782be6fcab4.png)
work ;/

**Comment by despa1r1337** [comment]
> There have been such mistakes recently. Can we solve them?
> 
> ![2020 01 10](https://user-images.githubusercontent.com/54233256/72090810-bc1f0480-3349-11ea-85e1-58a9bfada5c1.png)
> There have been repeated such mistakes, the reporting robot can not be used!
> ![20200110013903](https://user-images.githubusercontent.com/54233256/72090948-07d1ae00-334a-11ea-890f-819a3f1c6738.png)
> Above is my configuration.

?
