### ISSUE TITLE
Failed to report

### ISSUE THREAD

**Issue by chaingoc** [despa1r1337/ReportBot-v2#4]
Failed to report (19/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Phuc\\Downloads\\Compressed\\ReportBot-v2-master\\ReportBot-v2-master\\helpers\\GameCoordinator.js:124:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
![image](https://user-images.githubusercontent.com/50963198/78506248-8e0f5c00-77a2-11ea-86fa-d280406244b9.png)
tried 40 accounts

**Comment by despa1r1337** [comment]
reportbot only work when match finished,you can't reportbot player while they still have ongoing match ,you need to wait till match end,otherwise report will ignored and didnt get any response
