### ISSUE TITLE
Valve again Patched Commend/Report bot

### ISSUE THREAD

**Issue by amx22** [despa1r1337/ReportBot-v2#6]
wtf.. rip...

**Comment by trumeetration** [comment]
Bot logins, and then stucks. Seems, it cant send report properly

**Comment by amx22** [comment]
commend bot work but report bot blocked!!! dont sucesful report :@ pls fix @despa1r1337

**Comment by amx22** [comment]
https://github.com/BeepIsla/csgo-commend-bot/issues/418

**Comment by despa1r1337** [comment]
@amx22  the reporting system is disabled in the game itself :/ if you try to report, you will not see a successful report message.

**Comment by amx22** [comment]
no just deathmatch and casual servers disabled bro.. go competitive server try. work normal report own acc.

**Comment by despa1r1337** [comment]
> no just deathmatch and casual servers disabled bro.. go competitive server try. work normal report own acc.

did you report after the match?

**Comment by amx22** [comment]
yes i known. what I mean is that Valve completely removed the death match and simple entertainment servers reporting system

**Comment by Jaeger33211Sec** [comment]
> yes i known. what I mean is that Valve completely removed the death match and simple entertainment servers reporting system
> 
> yes end of game reporting still doesn't work..
> 
> go to death match with a normal account and try to report normally..
> 
> You cannot give because the valve has disabled the reporting system from those servers

Just btw, Reporting in MM still works fine

**Comment by amx22** [comment]
@Jaeger33211Sec Quote what I wrote 14 days ago xs i already found the fix 10 days ago
