### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mixer617** [despa1r1337/ReportBot-v2#8]
![Screenshot_1](https://user-images.githubusercontent.com/55286718/87424389-87d01d80-c5e4-11ea-8361-4679a772df07.png)
 
I don't know what sort of error is this, help me please

**Comment by despa1r1337** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/55286718/87424389-87d01d80-c5e4-11ea-8361-4679a772df07.png)
> 
> I don't know what sort of error is this, help me please

1) hi, use this version: https://github.com/BeepIsla/csgo-commend-bot

2.1) If you have such an error, then you need to open and edit config.json and set the number in reports, comments, as many as you have available. 
2.2) your accounts are being reloaded and you should wait 12 hours, or create new accounts
